---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: pierogi-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/gladion136/tuxedo-drivers-kmod/repo/fedora-%OS_VERSION%/gladion136-tuxedo-drivers-kmod-fedora-%OS_VERSION%.repo
    install:
      - niri
      - micro
      - starship
      - kitty
      - kitty-doc
      - kitty-kitten
      - kitty-terminfo
      - kitty-shell-integration
      - tuxedo-drivers-kmod
      - zoxide
      - direnv
      - waybar
      - openvpn
      - gopass
      - emacs
      - emacsclient
      - isync
      - maildir-utils
      - printer-driver-brlaser
      - clipman
      - distrobox
      - fzf
      - qutebrowser
      - foot
      - syncthing
      - nextcloud-client
      - pavucontrol
      - pinentry
      - rlwrap
      - vdirsyncer
      - wireguard-tools
      - zathura
      - wtype
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  - type: script
    snippets:
      - "echo $PATH"
      - "curl -o /tmp/eza.tar.gz -L https://github.com/eza-community/eza/releases/download/v0.22.1/eza_x86_64-unknown-linux-gnu.tar.gz"
      - "tar xvf /tmp/eza.tar.gz -C /tmp && ls -l /tmp && mv /tmp/eza /usr/bin/"
      - "curl -o /tmp/bat.tar.gz -L https://github.com/sharkdp/bat/releases/download/v0.25.0/bat-v0.25.0-x86_64-unknown-linux-gnu.tar.gz"
      - "tar --strip-components=1 -C /tmp -xvf /tmp/bat.tar.gz"
      - "ls -lha /tmp && mv /tmp/bat /usr/bin/bat"
      - "mv /tmp/autocomplete/bat.bash /usr/share/bash-completion/completions/bat.bash"
      - "bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)"
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: chezmoi
    repository: "https://github.com/bascht/dotfiles-public" # my dotfiles repo
    all-users: false
    file-conflict-policy: replace
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - IosevkaTermSlab
        - Lekton
        - VictorMono
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

